### ISSUE TITLE
在跑通『LLaVA单卡+gems』过程总遇到的 max.dim超过tensor最大元素数的 bug

### ISSUE THREAD

**Issue by 0x45f** [FlagOpen/FlagGems#304]
### Describe the bug

max.dim超过tensor最大元素数
![image](https://github.com/user-attachments/assets/a7777577-9438-48d3-92f4-4e74b3dbc5b0)

**Comment by haowen-han** [comment]
hanhaowen认领

**Comment by haowen-han** [comment]
最小demo：
```
import torch
import flag_gems

M, N, K = 4, 1048577, 4
A = torch.randn((M, N, K), dtype=torch.float16, device="cuda")
val_ref, index_ref = torch.max(A,dim=1)
with flag_gems.use_gems():
    val_flag, index_flag = torch.max(A,dim=1)

assert torch.allclose(val_flag,val_ref)

assert torch.allclose(index_ref,index_flag)

```
在master分支的8ef0859481cac05b8e5ea540ac7002615ebfb0c3 commit下，会报错：
```
/opt/conda/lib/python3.11/site-packages/torch/library.py:323: UserWarning: Warning only once for all operators,  other operators may also be overridden.
  Overriding a previously registered kernel for the same operator and the same dispatch key
  operator: aten::add.Tensor(Tensor self, Tensor other, *, Scalar alpha=1) -> Tensor
    registered at aten/src/ATen/RegisterSchema.cpp:6
  dispatch key: CUDA
  previous kernel: registered at ../aten/src/ATen/LegacyBatchingRegistrations.cpp:1079
       new kernel: registered at /dev/null:6 (Triggered internally at ../aten/src/ATen/core/dispatch/OperatorEntry.cpp:155.)
  self.m.impl(
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/triton/language/core.py", line 35, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/triton/language/core.py", line 1192, in arange
    return semantic.arange(start, end, _builder)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/triton/language/semantic.py", line 514, in arange
    ret_ty = tl.block_type(tl.int32, shape)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/triton/language/core.py", line 459, in __init__
    raise ValueError(f"numel ({self.numel}) exceeds triton maximum tensor numel ({TRITON_MAX_TENSOR_NUMEL})")
ValueError: numel (2097152) exceeds triton maximum tensor numel (1048576)

The above exception was the direct cause of the following exception:
```
